site_name: 簿記初級ラボ
site_url: "https://buno32.github.io/boki-shokyu-site/"
repo_url: ""
theme:
  name: material
  language: ja
  font: false

docs_dir: content
use_directory_urls: false

extra_css:
  - assets/css/site.css
  - assets/css/site-append-ch05.css
  # - assets/css/beginner-ch05.css   # （未使用: 存在しないため無効化）

nav:
  - はじめに: index.md
  - 第1章 簿記の基本原理: ch01/index.md
  - 第5章 現金・預金:
      - 章の目次: ch05/index.md
      - 1節 勘定の性質と増減: ch05/01-basics.md
      - 2節 よくある取引の型: ch05/02-patterns.md
      - 3節 資金移動・利息・手数料: ch05/03-transfers.md
      - 章末クイズ: ch05/99-quiz.md
  - デザイン見本:
      - レッスン見本: prototypes/lesson-sample.md
      - クイズ見本: prototypes/quiz-sample.md
      - 模擬試験見本: prototypes/exam-sample.md
      - ダッシュボード: prototypes/dashboard.md
      - タイポグラフィ: prototypes/typography.md


markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - tables
  - footnotes

plugins:
  - search

extra_javascript:
  - assets/js/quiz.js
  - assets/js/quiz.progress.patch.js   # ← 追加（順番は quiz.js の直後）
  - assets/js/exam.js
  - assets/js/dashboard.js
  # - assets/js/quiz.autoload.js  # （未使用: 存在しないため無効化）
