site_name: 簿記初級ラボ
site_url: "https://buno32.github.io/boki-shokyu-site/"
repo_url: ""
theme:
  name: material
  language: ja
  font: false
  features:
    - navigation.path       # パンくず
    - navigation.footer     # 前へ/次へ（フッター）
    - navigation.top        # トップに戻るボタン

docs_dir: content
use_directory_urls: false

extra_css:
  - assets/css/site.css

nav:
  - はじめに: index.md
  - 第1章 簿記の基本原理: ch01/index.md
  - 第5章 現金・預金:
      - 目次: ch05/index.md
      - 第1節 基本: ch05/01-basics.md
      - 第2節 パターン: ch05/02-patterns.md
      - 第3節 資金移動: ch05/03-transfers.md
      - 章末クイズ: ch05/99-quiz.md
  - デザイン見本:
      - レッスン見本: prototypes/lesson-sample.md
      - クイズ見本: prototypes/quiz-sample.md
      - 模擬試験見本: prototypes/exam-sample.md
      - ダッシュボード: prototypes/dashboard.md
      - タイポグラフィ: prototypes/typography.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - tables
  - footnotes

plugins:
  - search

extra_javascript:
  - assets/js/quiz.js
  - assets/js/exam.js
  - assets/js/dashboard.js
